### ISSUE TITLE
AppImage:unable to display enlarged image

### ISSUE THREAD

**Issue by maxmin2** [florianblume/6d-pat#149]
Hello, I have run the appimage(v2.4.2) on ubuntu 20.04. but the preview image's displaying box is not in right size and unable to display enlarged images. I impose my dataset configuration file(Default JSON file) may have some problem. Would you enjoy to share your dataset configuration as reference to help me figure out the problem?  
![6D](https://user-images.githubusercontent.com/42050745/143521792-300ad138-f6a6-4f11-89dc-7eb06cd8cdda.png)

**Comment by florianblume** [comment]
That's weird, displaying the image should have nothing to do with the poses JSON file. Could you post here the image you are trying to display (looks like LINEMOD or something?) together with the camera matrix file `info.json`?

**Comment by florianblume** [comment]
Were you able to solve the issue?

**Comment by florianblume** [comment]
Closing this issue now due to lack of activity. Reopen if the issue persists.
