### ISSUE TITLE
The annotation result image didn't show

### ISSUE THREAD

**Issue by sean6585** [florianblume/6d-pat#160]
I tried to annotate the image, but the result didn't show in the interface. The box just remained black, so I can't check my pose annotation. 
Software edition (6D-PAT): 2.5
Ubuntu version: 20.04
![Screenshot from 2022-06-29 20-16-09](https://user-images.githubusercontent.com/59359578/176433986-37473627-566b-4369-a926-df3d9d928286.png)

**Comment by florianblume** [comment]
Hey @sean6585,

that's pretty weird. Which dataset is that one again? I recognize it but cannot remember the name right now. Did you check the terminal output to see if there's any hint there what's happening?

Do you have camera matrices in the folder of the images? I guess there is one, otherwise the program wouldn't load the images but maybe the error lies in there since the images are shown in the gallery.

**Comment by florianblume** [comment]
Ah I see the name it's linemod right?

**Comment by florianblume** [comment]
I'm pretty busy right now due to a deadline but I'll try to help you find the error or have a quick look myself some time.

**Comment by sean6585** [comment]
Thank you for replying ! 
Yes, it is linemod dataset which I downloaded from the official website. 
I directly double clicked the AppImage file to open it, so there is no terminal output I can check.
As the picture shown below, I have created a info.json file which contains the camera parameters by following the format.

![Screenshot from 2022-06-29 21-20-27](https://user-images.githubusercontent.com/59359578/176447808-779c6f21-11ba-49e7-8aa6-6fa4aa470fac.png)

**Comment by florianblume** [comment]
Hm looking good to me... I'll try to see for myself what is wrong but I'm not sure when I can get to it due to the deadline :/ You could of course try to run the program from source and try to find out what's wrong.

**Comment by florianblume** [comment]
Could you upload your camera info file here? That would make it easier for me.

**Comment by sean6585** [comment]
Sorry, I might uploaded the wrong file
I used these files down below for testing, please check
[01.zip](https://github.com/florianblume/6d-pat/files/9015899/01.zip)

**Comment by florianblume** [comment]
That's weird, I cannot reproduce your problem. For me the images show up normally. Maybe add `{}` to your `poses.json` file, it's not a valid JSON file without at least the curly braces. I added some new code to automatically do that in the program but it's not pushed yet.

**Comment by florianblume** [comment]
Could you also try to run the AppImage from terminal? Using `./[appimage name]`. This way maybe the terminal outputs give away what the problem ist.

**Comment by sean6585** [comment]
Errors I got by running in terminal
![Screenshot from 2022-06-30 13-49-58](https://user-images.githubusercontent.com/59359578/176602437-9bb5f981-4556-400d-9ddd-df7c80d77ea0.png)

**Comment by sean6585** [comment]
And this is my OpenGL version
![Screenshot from 2022-06-30 14-09-36](https://user-images.githubusercontent.com/59359578/176605043-184e5f5c-544c-43cd-9cce-d47bfe7ccee4.png)

**Comment by florianblume** [comment]
I see, weird that the program works for me like this since it says that `varying` is deprecated after version 120 and I'm defining version 150 in the shader itself.

I'll try to commit a fix later.

**Comment by florianblume** [comment]
You can try the new [release](https://github.com/florianblume/6d-pat/releases/tag/v2.5.1), I modified the shader code and removed the old keywords that were causing the issue.

**Comment by sean6585** [comment]
I've tried version 2.5.1, then another errors come up
![Screenshot from 2022-07-01 11-04-57](https://user-images.githubusercontent.com/59359578/176815893-41476d89-e5a6-4022-9f1d-8e4fc4b7a11d.png)

**Comment by florianblume** [comment]
That's so weird, my OpenGL never complains. I'll push a new version  when I've got time.

**Comment by sean6585** [comment]
thank you for helping.

**Comment by florianblume** [comment]
Ok next try ;) https://github.com/florianblume/6d-pat/releases/tag/v2.5.2

**Comment by florianblume** [comment]
Does it work now finally?

**Comment by sean6585** [comment]
It works finally haha!!!!
Thank you very much!
![Screenshot from 2022-07-03 21-09-07](https://user-images.githubusercontent.com/59359578/177041251-363ef9d4-f711-45db-83fe-cd1014366312.png)

**Comment by florianblume** [comment]
Nice! :)

**Comment by willieChen58** [comment]
Hi, can i ask you some questions of annotation?

**Comment by willieChen58** [comment]
> Yes of course, please open a new issue for your question.
Thanks for your reply! I miss the problem just like that : when i'm clicking the points on the left image, it's so hard to achieve a success. I must try many times to get a point on the left image, but it's easy to click the points on the right model. Would you miss the problem like that? I wonder if it's only my problem, looking forward to your reply.

**Comment by florianblume** [comment]
Can you please open a new issue for this? When you click on issues, click on new issues. I'd like to keep the issues clean and to themselves and will not answer your question here directly. And can you maybe record a little video of what you mean exactly and post it in the _new_ issue (not here!)? So I can see what you mean exactly.

**Comment by willieChen58** [comment]
ok, I will open a new issue later.

**Comment by monajalal** [comment]
> If I'm not mistaking your camera info file specifies the image file ending as .png but they are jpgs. I manually changed the .png extension in the info file to jpg and was able to see the images. But it might be that I've got different images than you because the images in the downloaded dataset were of the form `000000.jpg`, so there were 2 more zeros than in your info file. Are you using a specific part of the downloaded images? I just extracted some images because the dataset is so huge.

it seems currently the app works for png images too.

![image](https://github.com/florianblume/6d-pat/assets/1892917/5f2bddf3-7dc6-4c5e-a69a-e2a0d45fa17c)
