### ISSUE TITLE
Failed to persist pose. Poses is not a file.

### ISSUE THREAD

**Issue by monajalal** [florianblume/6d-pat#168]
![Screenshot from 2024-04-22 14-39-57](https://github.com/florianblume/6d-pat/assets/1892917/67e52f7b-ccf7-4217-a09f-f862208e0a48)

I am just learning to use the app using your sample images (I know pose may be wrong). However, when I click on save button after recovering the pose post correspondence between the points on the 3D model and the RGB image, I get this error.

![Screenshot from 2024-04-22 14-39-23](https://github.com/florianblume/6d-pat/assets/1892917/bfd1b85e-c320-4990-9e25-91f647362e94)

This is what I had just before clicking on the save button.

Additionally, I want to rotate the duck overlaid on the RGB image. I am not able to. I am able to move along x, y, z axes though.

![Screenshot from 2024-04-22 14-45-37](https://github.com/florianblume/6d-pat/assets/1892917/e938c258-859f-433c-bb28-fb775ca1f8c6)

Could you please guide if there is a key for rotating? the duck is slightly not aligned.

[Screencast from 04-22-2024 02:49:56 PM.webm](https://github.com/florianblume/6d-pat/assets/1892917/f6c87c03-9e36-4d1a-878c-ac4dbfff4939)

Here is a screencast that showcases my correspondences and the recovered pose. However, I am not able to align the overlaid mesh with the duck on the RGB itself.

Please let me know if more information may be needed.

**Comment by florianblume** [comment]
Hey Mona,

1. Regarding the poses file: You get this error message if the path pointing to the file where to save the poses is not a file (e.g. because it is a directory). Can you check in the settings which path the poses file path points to?
2. Regarding rotation: Click on the grey sphere/circle of the gizmo. Maybe it would be useful if I added another key like "r" to switch to rotation.

Do you have additional problems to align the duck or just the mentioned ones?

**Comment by monajalal** [comment]
Hi Florian.

Thanks a lot for your correspondences.

I followed your instructions.

File --> Settngs --> Paths --> Poses file path and selected poses.json

and it worked.


```
{
    "000003.png": [
        {
            "R": [
                -0.9999866485595703,
                -0.004828471224755049,
                0.0018264712998643517,
                0.003642851719632745,
                -0.9106935262680054,
                -0.4130666255950928,
                0.003657836001366377,
                -0.4130544662475586,
                0.9106989502906799
            ],
            "id": "000003_PT2_meters_23.4.24_09:55:42",
            "obj": "PT2_meters.obj",
            "t": [
                0.5876601338386536,
                -0.17879125475883484,
                3.262895345687866
            ]
        }
    ]
}

```

**Comment by florianblume** [comment]
I will try to make the error message more meaningful in the future and maybe add the option to open the settings directly.
