### ISSUE TITLE
Color support for textured models

### ISSUE THREAD

**Issue by udopa** [florianblume/6d-pat#44]
Hello, is it possible to add the functionality to show the rendered object with its color/texture?

That would help tremendously when labeling symmetric objects.

**Comment by florianblume** [comment]
Hi udopa,

thank you for your comment. I didn't expect anyone to actually use the program and I'm happy that someone does. Unfortunately I won't be able to implement that functionality in quite a while as I'm in the middle of my master's thesis. But feel free to write it yourself and create a pull request! There are a lot of tutorials online how to render textured objects using OpenGL and Qt.

Cheers,
Florian

**Comment by florianblume** [comment]
Will be solved with issue #49
