### ISSUE TITLE
3D model doesn't appear on GUI

### ISSUE THREAD

**Issue by yyc9268** [florianblume/6d-pat#46]
Hi. 
This is a brilliant tool to annotate 6D pose simply connecting a few feature points.
I have successfully installed and built the 6d-pat using QT-creator.
However, the 3d model doesn't appear though I correctly designated the folder which contain mesh files. I have tried several model types like .ply and .stl, none of them works.
The image appears correctly.

The console outputs are as follows,

[GalleryObjectModelModel::onObjectModelRendered] (debug): "Preview rendering finished for oven_handle_whole_pc.stl.ply"
[unknown] (warning): QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
[GalleryObjectModelModel::onObjectModelRendered] (debug): "Preview rendering finished for Plastic_bolt.ply"

I havn't modified any source code.
Could you guess the reason why dont the 3D model appear at all?

**Comment by yyc9268** [comment]
I may have found a reason. Though the model files are in same format (e.g., ply, stl), only the binary file works, ASCII file fails.

**Comment by florianblume** [comment]
Hey, thanks for your comment, I'm glad you're enjoying using the program! Although I know it still has a lot of bugs/issues to it ;) If you find a bug and repair it, create a merge request and I'll have a look at it! I'm happy you found the reason for why the model wasn't showing up, although I'm unsure why plain ASCII files don't work...

**Comment by florianblume** [comment]
Maybe related to #93
