### ISSUE TITLE
libGL error on Installation

### ISSUE THREAD

**Issue by tom-garford** [florianblume/6d-pat#98]
Hi Florian, 

Great looking software, thanks for sharing. Just trying to use the docker image you have provided. I have tried using this with an Ubuntu 16.04 and 18.04 machine with proprietary Nvidia drivers installed (415 & 435) and can get to the splash screen before a segmentation fault. 

I am always met by this error: 

`docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix florianblume/6dpat
[unknown] (warning): QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[unknown] (warning): QFileSystemWatcher::removePath: path is empty
[unknown] (warning): QFileSystemWatcher::removePath: path is empty
[unknown] (warning): QFileSystemWatcher::removePath: path is empty
[unknown] (warning): QOpenGLFunctions created with non-current context
Segmentation fault (core dumped)
`

I have tried hard to debug this error by going through mainly Steam-related threads on Google with this problem. However, reinstalling Nvidia drivers, looking for problematic mesa drivers, etc. makes no difference. I can run glxgears on my system proving OpenGL is working and installed nvidia-docker, however this makes no difference. 

I have also tried on a Jetson Nano device with preinstalled drivers, docker, etc. but am met by a "exec user process caused exec format error" so have not pursued this much further. 

Any assistance would be great! 

Kind regards, Tom. 

P.S. I have also tried the docker image for just installing the environment but am met by the same issue.

**Comment by tom-garford** [comment]
Ah, it looks like I haven't been paying proper attention to #80 . I'll make sure to export the variables and report  back if I have a problem.

**Comment by tom-garford** [comment]
Have now installed locally with no issues. Will put this down to my docker incompetence. Apologies

**Comment by florianblume** [comment]
Could you tell me which variables you needed to export?
These ones?
`export PATH="/usr/lib/nvidia-410/bin":${PATH}
export LD_LIBRARY_PATH="/usr/lib/nvidia-410:/usr/lib32/nvidia-384":${LD_LIBRARY_PATH}
./6D-PAT`
Because if so I'll add this to the setup manual so that others know of this, too.

**Comment by tom-garford** [comment]
Hi Florian, 

When doing a local install I didn't have to export any variables at all. I don't think I was correctly exporting the variables you describe when doing the docker method, hence my swarst problems. As the local method worked, I didn't investigate this any further however.
